"""add_password_reset_fields

Revision ID: 3f95d27c640f
Revises: 7996f95d3283
Create Date: 2025-10-13 12:03:35.683237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f95d27c640f'
down_revision: Union[str, Sequence[str], None] = '7996f95d3283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_progress_id'), table_name='resume_progress')
    op.drop_index(op.f('ix_resume_progress_resume_id'), table_name='resume_progress')
    op.drop_table('resume_progress')
    op.add_column('resumes', sa.Column('customization', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('share_links_token_key'), 'share_links', type_='unique')
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.create_unique_constraint(op.f('share_links_token_key'), 'share_links', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('resumes', 'customization')
    op.create_table('resume_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('section_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('resume_progress_resume_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_progress_pkey'))
    )
    op.create_index(op.f('ix_resume_progress_resume_id'), 'resume_progress', ['resume_id'], unique=True)
    op.create_index(op.f('ix_resume_progress_id'), 'resume_progress', ['id'], unique=False)
    # ### end Alembic commands ###
